source 'http://rubygems.org'
gem 'rails', '4.1.5'
gem 'sqlite3'
gem 'sass-rails', '~> 4.0.3'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'bootstrap-sass', '~> 3.3.4.1'
gem 'angularjs-rails', '~> 1.3.15'
gem 'capybara'
gem 'factory_girl'
gem 'jbuilder', '~> 2.0'
gem 'aws-s3', '~> 0.6.3',:require => 'aws/s3'
gem 'sdoc', '~> 0.4.0',          group: :doc
gem 'spring',        group: :development
gem 'haml', '~> 4.0.5'
gem 'simple_form', '~> 3.0.2'
gem 'devise', '~> 3.4.1'
gem 'acts_as_votable', '~> 0.10.0'
gem 'paperclip', '~> 4.2.0'
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw]
gem 'rack-attack'